"""Deterministic, plain-English explanations for every exception.

The project's thesis is that an unresolved line is escalated with a typed reason and a
readable account of *why*, rather than silently dropped or guessed at. Before this
module, `Exception_.explanation` was populated only from tier3's own reasoning -- which
meant the flagship `--no-llm` demo path (the one that runs with zero API keys) escalated
everything with `explanation=None`, and a reviewer opening the queue saw a reason code
and nothing else. The evidence needed to write a real sentence was already computed by
tier2; it just never reached the reviewer.

Every figure quoted here is computed by the pipeline, never generated by a model. When
tier3 *has* weighed in, its reasoning is appended as a clearly-labelled note rather than
replacing this text -- so the numbers in an explanation are always machine-derived and a
model can add narrative around them but can never alter a number a reviewer acts on.
That is the same containment argument the adjudicator's fixed candidate menu makes,
applied to the explanation surface. See IMPLEMENTATION.md sections 4 and 5.
"""

from __future__ import annotations

from datetime import date

from ledgerloop.ingest.normalise import NormalisedBankLine
from ledgerloop.match.tier1_exact import SettlementBatch
from ledgerloop.schemas import Candidate, UnresolvedCase

# Rules tier2 records in candidate evidence, rendered for a human reader. An unknown
# rule falls back to its raw key rather than being hidden -- an explanation that says
# something slightly awkward is strictly better than one that omits how a match was found.
_RULE_PROSE: dict[str, str] = {
    "utr_amount_tolerance": "UTR match within amount tolerance",
    "utr_single_transposition_tolerant": "UTR match allowing a single digit transposition",
    "amount_date_fallback_no_utr": "amount and date match with no UTR present",
    "generic_cross_batch_subset_sum": "cross-batch subset-sum search",
    "utr_partition_search": "UTR batch split across two credits",
}


def _group_indian(n: int) -> str:
    """Indian digit grouping: last three digits, then pairs (1,00,00,000 not 10,000,000)."""
    s = str(n)
    if len(s) <= 3:
        return s
    head, tail = s[:-3], s[-3:]
    parts: list[str] = []
    while len(head) > 2:
        parts.insert(0, head[-2:])
        head = head[:-2]
    if head:
        parts.insert(0, head)
    return ",".join(parts) + "," + tail


def format_paise(paise: int, symbol: str = "₹") -> str:
    """Integer paise -> display rupees. Uses divmod, never float division: this string
    is what a reviewer reads off the queue before approving a posting, so it must not
    inherit a binary-floating-point rounding artefact.

    symbol is overridable because the CLI reports are echoed to a Windows console that
    is not reliably UTF-8, and a report that raises UnicodeEncodeError halfway through
    is worse than one that says "Rs." -- eval/metrics.py passes the ASCII form.
    """
    sign = "-" if paise < 0 else ""
    whole, frac = divmod(abs(paise), 100)
    return f"{sign}{symbol}{_group_indian(whole)}.{frac:02d}"


def rupees(paise: int) -> str:
    """format_paise with the rupee sign, for UTF-8-safe surfaces (the dashboard, JSON,
    and the exception explanations themselves)."""
    return format_paise(paise)


def _when(value_date: date) -> str:
    return value_date.strftime("%d %b %Y")


def _rule_prose(candidate: Candidate) -> str:
    rule = candidate.evidence.get("rule", "")
    return _RULE_PROSE.get(rule, rule.replace("_", " ") if rule else "an unnamed strategy")


def _best(case: UnresolvedCase) -> Candidate | None:
    return max(case.candidates, key=lambda c: c.score) if case.candidates else None


def _opening(bank_line: NormalisedBankLine) -> str:
    return f"Bank credit of {rupees(bank_line.credit_amount_paise)} on {_when(bank_line.value_date)}"


def _low_confidence(bank_line: NormalisedBankLine, case: UnresolvedCase, cfg: dict) -> str:
    best = _best(case)
    if best is None:  # defensive: LOW_CONFIDENCE without candidates shouldn't occur
        return f"{_opening(bank_line)} scored below the resolve threshold with no candidate retained."
    diff = best.evidence.get("amount_diff_paise")
    gap = f", leaving a {rupees(diff)} difference" if isinstance(diff, int) and diff else ""
    return (
        f"{_opening(bank_line)}. The strongest of {len(case.candidates)} candidate(s) groups "
        f"{len(best.matched_txn_ids)} transaction(s) by {_rule_prose(best)}{gap}, but scores "
        f"{best.score:.2f} against a {cfg['min_resolve_score']:.2f} resolve threshold. "
        f"Escalated for review rather than matched on a weak signal."
    )


def _ambiguous(bank_line: NormalisedBankLine, case: UnresolvedCase, cfg: dict) -> str:
    best = _best(case)
    top = f"{best.score:.2f}" if best else "n/a"
    tied = [c for c in case.candidates if best and best.score - c.score <= cfg["ambiguity_margin"]]
    return (
        f"{_opening(bank_line)}. {len(tied)} of {len(case.candidates)} candidate(s) score within "
        f"{cfg['ambiguity_margin']:.2f} of the {top} top score, so no single grouping is "
        f"defensibly the right one. Escalated rather than picking arbitrarily between them."
    )


def _amount_mismatch(bank_line: NormalisedBankLine, batch: SettlementBatch | None, cfg: dict) -> str:
    if batch is None:  # defensive: classify() only assigns this code when a batch was found
        return (
            f"{_opening(bank_line)} links to a settlement batch by UTR, but the amounts differ by "
            f"more than the {rupees(cfg['amount_tolerance_paise'])} tolerance."
        )
    diff = abs(bank_line.credit_amount_paise - batch.total_net_paise)
    return (
        f"{_opening(bank_line)} carries UTR {bank_line.extracted_utr}, which identifies settlement "
        f"batch {batch.settlement_batch_id} ({len(batch.txn_ids)} transaction(s), net "
        f"{rupees(batch.total_net_paise)}). The {rupees(diff)} difference exceeds the "
        f"{rupees(cfg['amount_tolerance_paise'])} tolerance. The linkage is near-certain, so this "
        f"is an amount discrepancy for a human to price, not a matching failure."
    )


def _suspected_duplicate(bank_line: NormalisedBankLine, cfg: dict) -> str:
    return (
        f"{_opening(bank_line)} matched no settlement batch, but two or more unclaimed gateway "
        f"transactions carry the same gross amount within {rupees(cfg['amount_tolerance_paise'])} "
        f"-- the signature of a double charge. Escalated for duplicate review rather than matched "
        f"to whichever transaction happened to sort first."
    )


def _no_candidate(bank_line: NormalisedBankLine, cfg: dict) -> str:
    utr = (
        f"Its UTR {bank_line.extracted_utr} matched no unclaimed batch"
        if bank_line.extracted_utr
        else "No UTR could be extracted from the narration"
    )
    return (
        f"{_opening(bank_line)} could not be attributed. {utr}, and no combination of settlement "
        f"lines within the {cfg['date_window_days']}-day window sums to it within "
        f"{rupees(cfg['amount_tolerance_paise'])}. Nothing is proposed."
    )


def _tier2_timeout(bank_line: NormalisedBankLine, cfg: dict) -> str:
    return (
        f"{_opening(bank_line)} exhausted the subset-sum search budget "
        f"({cfg['subset_sum_node_budget']:,} nodes) before finding any combination of settlement "
        f"lines summing to it within {rupees(cfg['amount_tolerance_paise'])}. A partial search is "
        f"reported as unresolved rather than as evidence that no match exists."
    )


def _out_of_scope(bank_line: NormalisedBankLine) -> str:
    return (
        f"{_opening(bank_line)} carries no extractable UTR or RRN and matches no settlement batch. "
        f"It most likely is not a gateway settlement at all -- a direct customer transfer, an "
        f"inter-account move, or a refund reversal. Routed out of reconciliation scope rather than "
        f"forced onto the nearest-looking batch."
    )


def _tier3_invalid(bank_line: NormalisedBankLine, case: UnresolvedCase) -> str:
    return (
        f"{_opening(bank_line)} was sent to adjudication with {len(case.candidates)} candidate(s), "
        f"but every response named a selection outside that menu. The responses were discarded and "
        f"the line escalated -- an out-of-menu answer is never accepted as a match."
    )


def build_explanation(
    bank_line: NormalisedBankLine,
    case: UnresolvedCase,
    reason_code: str,
    tier2_cfg: dict,
    *,
    near_utr_batch: SettlementBatch | None = None,
) -> str:
    """The deterministic explanation for one exception. Always returns a non-empty string:
    a reviewer must never be handed a bare reason code."""
    if reason_code == "LOW_CONFIDENCE":
        return _low_confidence(bank_line, case, tier2_cfg)
    if reason_code == "AMBIGUOUS_CANDIDATES":
        return _ambiguous(bank_line, case, tier2_cfg)
    if reason_code == "AMOUNT_MISMATCH_BEYOND_TOLERANCE":
        return _amount_mismatch(bank_line, near_utr_batch, tier2_cfg)
    if reason_code == "SUSPECTED_DUPLICATE":
        return _suspected_duplicate(bank_line, tier2_cfg)
    if reason_code == "TIER2_TIMEOUT":
        return _tier2_timeout(bank_line, tier2_cfg)
    if reason_code == "OUT_OF_SCOPE":
        return _out_of_scope(bank_line)
    if reason_code == "TIER3_INVALID_SELECTION":
        return _tier3_invalid(bank_line, case)
    if reason_code == "REVIEWER_REJECTED":
        return _reviewer_rejected(bank_line, case)
    return _no_candidate(bank_line, tier2_cfg)


def _reviewer_rejected(bank_line: NormalisedBankLine, case: UnresolvedCase) -> str:
    """A line whose every remaining option a human already turned down.

    Says so plainly rather than reporting a score, because the machine has no doubt here
    and quoting one would misdescribe why the line is in the queue. The reviewer's own
    attribution is appended by taxonomy.classify from the decision record."""
    count = len(case.candidates)
    one = count == 1
    return (
        f"{_opening(bank_line)}. "
        f"{'The only candidate' if one else f'All {count} candidates'} for this line "
        f"{'is' if one else 'are'} a pairing a reviewer has already rejected, so "
        f"{'it was' if one else 'they were'} not proposed again and no model was asked to "
        "reconsider. The credit is still unexplained and needs a match nobody has found yet."
    )


def candidate_details(case: UnresolvedCase) -> list[dict]:
    """Per-candidate detail for the evidence payload. `Exception_.candidates_considered`
    is a `list[str]` by interface contract (IMPLEMENTATION.md section 5) and stays that
    way; the actual transaction IDs and amounts a reviewer needs to act ride here in
    evidence instead of being hidden behind opaque candidate handles like BANK00115-C0.
    """
    return [
        {
            "candidate_id": c.candidate_id,
            "score": round(c.score, 4),
            "rule": c.evidence.get("rule"),
            "txn_count": len(c.matched_txn_ids),
            "matched_txn_ids": c.matched_txn_ids,
            "amount_diff_paise": c.evidence.get("amount_diff_paise"),
        }
        for c in sorted(case.candidates, key=lambda c: -c.score)
    ]
